#!/bin/bash

TRACE=false
dataFile="TEMP_$$"
usingTemp=true
syntaxMessage="./stats {-rows | -cols} [file]"

function averageAll
{
	sum=0
	count=0
	while read line
	do
		sum=`expr $sum + $line`
		count=`expr $count + 1`
	done
	
	#half-round-up magic
	expr \( $sum + \( $count / 2 \) \) / $count
}

#for use in median
function max
{
	if [ $1 -gt $2 ]
	then
		echo $1
	else
		echo $2
	fi
}

function median
{
	#calculate indices
	mididx=`expr $1 / 2`
	nextidx=`expr $mididx + 1`

	#save stdin for later, also sorts for median purposes	
	data=`cat | sort -n`

	#gets values at middle indices
	mid=`echo "$data" | head -n$mididx | tail -n1`
	nextmid=`echo "$data" | head -n$nextidx | tail -n1`

	#if there is an odd amount of numbers, then just pick the middle one
	if [[ `expr "$1" % 2`  == 1 ]]
	then
		echo $nextmid
	else
		#largest of two middle-est numbers
		echo `max $mid $nextmid`
	fi
}

#check number of arguments
if [ "$#" = "1" ]
then #no file given, write stdin to a temp file
	$TRACE && echo "Creating temp file"

	#trap statement is only active if we are using a temp file
	trap "rm $dataFile; exit 1" INT TERM KILL HUP
	cat > "$dataFile"

elif [ "$#" = "2" ]
then #file argument given
	#set up variables
	dataFile=$2
	usingTemp=false

	#check for file exists
	if [ ! -f $dataFile ]
	then
		echo "./stats: no such file: $dataFile" >&2
		exit 1

	#check for read permissions
	elif [ ! -r $dataFile ]
	then
		echo "./stats: cannot read file: $dataFile" >&2
		exit 1
	fi

	$TRACE && echo "Using file $dataFile"
else #clearly someone made a mistake
	echo $syntaxMessage
	exit 1
fi

cols=`head -n1 $dataFile | wc -w`
rows=`cat $dataFile | wc -l`

$TRACE && echo "$rows rows, $cols cols"

#check for rows/columns argument
if [[ $1 == -r* ]]
then
	$TRACE && echo "baking row function"

	#extracts a row of data from stdin
	function getData
	{
		cat $dataFile | head -n$1 | tail -n1 | tr '\t' '\n'
	}

	#calculate and format output
	echo -e "Average\tMedian" 

	for i in `seq 1 $rows`
	do
		avg=`getData $i | averageAll`
		med=`getData $i | median $cols`
		echo -e "$avg\t$med" 
	done

elif [[ $1 == -c* ]]
then
	$TRACE && echo "baking column function"

	#extracts a column of data from stdin
	function getData
	{
		cat $dataFile | cut -f$1
	}

	#calculate and format output
	echo -n -e "Average:\t" 

	for i in `seq 1 $cols`
	do
		avg=`getData $i | averageAll`
		echo -n -e "$avg\t" 
	done

	echo -n -e "\nMedian :\t" 

	for i in `seq 1 $cols`
	do
		med=`getData $i | median $rows`
		echo -n -e "$med\t" 
	done
	echo "" 

else #not row or column argument
	echo $syntaxMessage
	exit 1
fi

#Remove temporary file if we were using it
$usingTemp && rm $dataFile

exit 0

